apiVersion: v1
kind: Service
metadata:
  name: {{ include "python.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "python.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  {{- if .Values.containerPorts.python }}
    - port: 8080
      targetPort: python
      protocol: TCP
      name: python
  {{- end }}
  {{- if .Values.containerPorts.sshd }}
    - port: 22
      targetPort: sshd
      protocol: TCP
      name: sshd
  {{- end }}
  selector:
    {{- include "python.selectorLabels" . | nindent 4 }}
