apiVersion: v1
kind: Service
metadata:
  name: {{ include "ruby.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ruby.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  {{- if .Values.containerPorts.ruby }}
    - port: 8080
      targetPort: ruby
      protocol: TCP
      name: ruby
  {{- end }}
  {{- if .Values.containerPorts.sshd }}
    - port: 22
      targetPort: sshd
      protocol: TCP
      name: sshd
  {{- end }}
  selector:
    {{- include "ruby.selectorLabels" . | nindent 4 }}
